# Site settings
title: WildCall    				  	#你博客的标题
SEOTitle: 野生物语 | WildCall Blog    	 #显示在浏览器上搜索的时候显示的标题
header-img: assets/css/images/bg.jpg	#显示在首页的背景图片
email: neomx7@gmail.com	
description: "杂家的博客"  			 #网站介绍
keyword: "IT Blog" #关键词
url: "https://neomx7.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings  侧边栏
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "..."
sidebar-avatar: /assets/css/images/home/morty.png      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# SNS settings  社交账号
RSS: false
github_username:    neomx7
jianshu_username:   7d51d931d352



# Disqus settings（https://disqus.com/）  评论
disqus_username: neomx7

# Analytics settings
# Baidu Analytics
## ba_track_id: 83e259f69b37d02a4633a2b7d960139c

# Google Analytics
ga_track_id: 'UA-124495208-1'            # Format: UA-xxxxxx-xx
ga_domain: auto